### ISSUE TITLE
add a Readme and better project name?

### ISSUE THREAD

**Issue by bobzhang** [OvermindDL1/bucklescript-testing#2]

**Comment by OvermindDL1** [comment]
I am planning to pull OAK-TEA out into its own repository soon.  I've been integrating bsb into my projects directly and am building up a tutorial post on how to use it (and specifically how to integrate it into the Phoenix server as that is what I use for the back-end, oh how I wish ocaml could compile to the EVM/BEAM so I could have it on both the front and back ends...).  :-)

Should not be long now though, holidays finally over.  ^.^

**Comment by bobzhang** [comment]
@OvermindDL1 Enjoy your holiday! I think it is valuable to have a pure ocaml implementation UI library and like to contribute to it (pardon that I am a newbie)

**Comment by OvermindDL1** [comment]
> @OvermindDL1 Enjoy your holiday! I think it is valuable to have a pure ocaml implementation UI library and like to contribute to it (pardon that I am a newbie)

Agreed entirely, being purely OCaml allows for a *LOT* of optimization opportunities (as well as examples).  If only OCaml had dependent type support, then could decorate the FFI with more information.  ^.^

I'm hoping to be able to rewrite the chunks I made that I do not like here soon, then can export to github.

I'm also still looking for a good PPX guide and docs as I am really interested on making an OCaml->EVM/BEAM converter.  OCaml would be such a perfect fit in the EVM's process model for the back-end while bucklescript handles the javascript side.  :-)

**Comment by fineline** [comment]
Hi, a bit OT, but just wanted to chime in and thank you for this work Overmind. I've been following Elm for a while, and BuckleScript since the 1.0 announcement. Elm is great, but I feel the imperative capabilities of OCaml might make for better interaction with "the real world" (i.e. everything outside the functional runtime) and BuckleScript's FFI looks good for that too. Plus OCaml has great reach (perhaps not the BEAM yet - interesting concept Overmind - but the language certainly has capability for server-side, native, and even unikernel and microcontroller). All my (long) career I've been interested to find a good general purpose language, and currently OCaml is looking interesting.

I have found the lack of a UI framework for OCaml/BuckleScript frustrating. I have looked into the work the Reason guys are doing to provide React bindings, and also looked into Yaron Minsky's incremental DOM project, but not found them to be really usable (yet). I'm looking forward to trying out Oak-Tea.

How are you a newbie bobzhang? Isn't BuckleScript your project?

**Comment by OvermindDL1** [comment]
> Hi, a bit OT, but just wanted to chime in and thank you for this work Overmind. I've been following Elm for a while, and BuckleScript since the 1.0 announcement. Elm is great, but I feel the imperative capabilities of OCaml might make for better interaction with "the real world" (i.e. everything outside the functional runtime) and BuckleScript's FFI looks good for that too. Plus OCaml has great reach (perhaps not the BEAM yet - interesting concept Overmind - but the language certainly has capability for server-side, native, and even unikernel and microcontroller). All my (long) career I've been interested to find a good general purpose language, and currently OCaml is looking interesting.

Yeah I think OCaml would be just the typed language that the BEAM needs.  BEAM is compilable to a micro-os ([Nerves](http://nerves-project.org/)), it is designed for up-time in the face of all else, and I'm quite sure I've worked out how to apply types to all parts of the platform, just need to learn the OCaml compiler (though I'd love to get it as another back-end 'in' bucklescript, some of its optimizations for javascript would be *highly* useful, especially in terms of multi-arity).

> I have found the lack of a UI framework for OCaml/BuckleScript frustrating. I have looked into the work the Reason guys are doing to provide React bindings, and also looked into Yaron Minsky's incremental DOM project, but not found them to be really usable (yet). I'm looking forward to trying out Oak-Tea.

You can pull out the files here and try it now if you want, it is *very* Elm'y in how it works.  I'm going to clean up the internals but the interface should stay identical when I finish up and make it a stand-alone library.  I also plan to add in custom-element support to be able to make webcomponent style things (optionally of course) as that is the main way I make elements at work.

> How are you a newbie bobzhang? Isn't BuckleScript your project?

He is new to web work (I think?), I am too technically, only past few years (I do mainly server back-end work via C++ and Erlang with a variety of languages for private projects like OCaml/Rust/Etc...), so it is a learning bit for us both.  :-)

**Comment by OvermindDL1** [comment]
And done:  https://github.com/OvermindDL1/bucklescript-tea

This repository will remain for my testing for now.  Now that the TEA API is pulled out into its own repo this will eventually be updated to pull from that repo as well.

Closing.  :-)
