### ISSUE TITLE
Build fail because no bsconfig.json?

### ISSUE THREAD

**Issue by fishmacs** [OvermindDL1/bucklescript-testing#4]
Compile Issues of tea_svg_events.ml :
Fatal error: exception Failure("File \"ext_filename.ml\", line 205, characters 13-20bsconfig.json not found from /")
...
...

**Comment by OvermindDL1** [comment]
Yeah this project was primarily for initial testing of what became https://github.com/OvermindDL1/bucklescript-tea and if you want to compile this it really does need the old version of bucklescript before it added its build system, so version 1.1 or 1.2 or so, it will not work on the newer bucklescript unless I add support for its new (and much better) build system.  :-)

All features for the TEA style interface and library are in the above bucklescript-tea project, this is primarily just examples I originally made for testing, but they can still be used for code examples on 'how' to use `bucklescript-tea` as the interface is near-enough identical.  You should be able to copy most of the examples from here to use in bucklescript-tea unmodified except for the occasional event handler that had minor changes.  :-)

PR's are welcome if you or anyone else want to upgrade this to use Bucklescript's build system, but for now I'll keep taking it apart piece by piece as I build up examples linked to the main bucklescript-tea project, but otherwise not doing much here itself.  :-)

**Comment by fishmacs** [comment]
Ok, I see.
I failed install older bs-platform then, now I have the version 1.2 installed.
How about bucklescript-tea? Can it be used in real world projects?

Thanks!

**Comment by OvermindDL1** [comment]
> How about bucklescript-tea? Can it be used in real world projects?

Yep, I'm using it in production and multiple others have been testing and sending PR's and such, as well as the creator of Bucklescript shows up on occasion to use bucklescript-tea as testing for Bucklescript features (especially making sure the Bucklescript Build system works properly with libraries), so at the very least he will ensure it works.  ^.^

**Comment by OvermindDL1** [comment]
> I failed install older bs-platform then, now I have the version 1.2 installed.

Yeah it was much more finicky back then.  If you are on a mac or linux it should work decently without issue once the pre-reqs are installed (OCaml and such), but Windows was more troublesome.  Nowadays Bucklescript installs fine about everywhere.  :-)

**Comment by fishmacs** [comment]
How about tea comparing with similar libs, say rehydrate?

**Comment by OvermindDL1** [comment]
> rehydrate

Isn't that just building on React?

**Comment by fishmacs** [comment]
Yeah, so, maybe just as elm vs react?

2017年3月1日 23:52，"OvermindDL1" <notifications@github.com>写道：

**Comment by OvermindDL1** [comment]
> Yeah, so, maybe just as elm vs react?

Exactly.  :-)

Basically, React is more just the 'V' in 'MVC', you still need to handle the 'MC' parts, and since React assumes mutability it will always have a speed hit compared to the equivalent immutable VDOM, however creating the VDOM could potentially be faster on later updates (though that has not panned out in my tests, bucklescript-tea is *significantly* faster than react in handling the VDOM).

The TEA style is the complete MVC in comparison.  :-)

**Comment by fishmacs** [comment]
I created my own [repository](https://github.com/fishmacs/bucklescript-tea-sample) of bucklescript samples, very few modification.

Most of the samples work properly but problem with HTTP testing:

> Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': The object's state must be OPENED.

**Comment by OvermindDL1** [comment]
Changes in recent bucklescript versions have changed how name encoding works, the main tea repo has an open issue about it.  :-)
